
"""
srtm_tools.py

Reusable module to download multiple SRTM tiles, mosaic them, and rotate the resulting DEM.

Author: Volker Rath (DIAS)
Generated by Copilot v1.0
Date: 2025-11-27

Remarks
-------
- Tiles are fetched from USGS SRTM v2.1 archive (SRTM3, 3 arc-second).
- Filenames follow convention: N45E006.hgt.zip under continent directories (e.g., Eurasia).
- Rotation is applied via affine transform; for grid alignment, consider reprojection.

"""

import os
import math
import requests
import zipfile
import numpy as np
import rasterio
from rasterio.merge import merge
from rasterio import Affine
from rasterio.warp import reproject, Resampling


def tiles_for_bbox(lat_min, lat_max, lon_min, lon_max):
    """
    Enumerate SRTM tile names for a bounding box.

    Parameters
    ----------
    lat_min, lat_max : float
        Latitude bounds.
    lon_min, lon_max : float
        Longitude bounds.

    Returns
    -------
    list of str
        Tile names like 'N45E006'.
    """
    lats = range(math.floor(lat_min), math.ceil(lat_max))
    lons = range(math.floor(lon_min), math.ceil(lon_max))
    tiles = []
    for lat in lats:
        for lon in lons:
            ns = 'N' if lat >= 0 else 'S'
            ew = 'E' if lon >= 0 else 'W'
            tiles.append(f"{ns}{abs(lat):02d}{ew}{abs(lon):03d}")
    return tiles


def download_srtm_tile(tile, continent="Eurasia", out_dir="srtm"):
    """
    Download and unzip a single SRTM tile.

    Parameters
    ----------
    tile : str
        Tile name (e.g., 'N45E006').
    continent : str
        Continent directory in USGS archive.
    out_dir : str
        Output directory.

    Returns
    -------
    str
        Path to extracted .hgt file.
    """
    os.makedirs(out_dir, exist_ok=True)
    url = f"https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/{continent}/{tile}.hgt.zip"
    zpath = os.path.join(out_dir, f"{tile}.hgt.zip")
    hgt_path = os.path.join(out_dir, f"{tile}.hgt")

    if not os.path.exists(hgt_path):
        r = requests.get(url, timeout=60)
        r.raise_for_status()
        with open(zpath, "wb") as f:
            f.write(r.content)
        with zipfile.ZipFile(zpath) as zf:
            zf.extractall(out_dir)
    return hgt_path


def mosaic_hgt(hgt_paths, out_path="srtm_mosaic.tif"):
    """
    Mosaic multiple HGT tiles into a single GeoTIFF.

    Parameters
    ----------
    hgt_paths : list of str
        Paths to .hgt files.
    out_path : str
        Output GeoTIFF path.

    Returns
    -------
    str
        Path to mosaic GeoTIFF.
    """
    srcs = [rasterio.open(p) for p in hgt_paths]
    mosaic, out_trans = merge(srcs)
    meta = srcs[0].meta.copy()
    meta.update({
        "height": mosaic.shape[1],
        "width": mosaic.shape[2],
        "transform": out_trans,
        "driver": "GTiff"
    })
    with rasterio.open(out_path, "w", **meta) as dst:
        dst.write(mosaic)
    for s in srcs:
        s.close()
    return out_path


def rotate_raster(in_path, out_path, angle_deg):
    """
    Rotate a raster by an angle using affine transform.

    Parameters
    ----------
    in_path : str
        Input raster path.
    out_path : str
        Output rotated raster path.
    angle_deg : float
        Rotation angle in degrees.

    Returns
    -------
    str
        Path to rotated raster.
    """
    with rasterio.open(in_path) as src:
        data = src.read(1)
        src_transform = src.transform
        src_crs = src.crs

        rot = Affine.rotation(angle_deg)
        dst_transform = rot * src_transform

        dst_meta = src.meta.copy()
        dst_meta.update({
            "transform": dst_transform,
            "height": src.height,
            "width": src.width
        })

        dst_data = np.empty((1, src.height, src.width), dtype=src.dtypes[0])
        with rasterio.open(out_path, "w", **dst_meta) as dst:
            reproject(
                source=data,
                destination=dst_data[0],
                src_transform=src_transform,
                src_crs=src_crs,
                dst_transform=dst_transform,
                dst_crs=src_crs,
                resampling=Resampling.bilinear
            )
            dst.write(dst_data)
    return out_path


def geotiff_to_xyz(in_path, out_path="output.xyz"):
    with rasterio.open(in_path) as src:
        band = src.read(1)
        rows, cols = np.where(band != src.nodata)
        xs, ys = src.xy(rows, cols)
        zs = band[rows, cols]

        with open(out_path, "w") as f:
            for x, y, z in zip(xs, ys, zs):
                f.write(f"{x:.6f} {y:.6f} {z:.2f}\n")

    return out_path

def process_srtm(lat_min, lat_max, lon_min, lon_max, angle_deg, continent="Eurasia", out_dir="srtm"):
    """
    Full pipeline: enumerate, download, mosaic, rotate.

    Parameters
    ----------
    lat_min, lat_max, lon_min, lon_max : float
        Bounding box coordinates.
    angle_deg : float
        Rotation angle in degrees.
    continent : str
        Continent directory in USGS archive.
    out_dir : str
        Output directory.

    Returns
    -------
    str
        Path to rotated DEM.
    """
    tiles = tiles_for_bbox(lat_min, lat_max, lon_min, lon_max)
    hgt_files = [download_srtm_tile(t, continent=continent, out_dir=out_dir) for t in tiles]
    mosaic_path = mosaic_hgt(hgt_files, out_path=os.path.join(out_dir, "srtm_mosaic.tif"))
    rotated_path = rotate_raster(mosaic_path, os.path.join(out_dir, "srtm_mosaic_rot.tif"), angle_deg)
    return rotated_path
