"""
femtic_plot_distort.py
=======================

Plot FEMTIC static (frequency-independent) galvanic distortion matrices as
distortion ellipses on a map, optionally over an SRTM-derived hillshade
basemap, and optionally as a 2x2 panel of Groom-Bailey decomposition
parameters (twist, shear, gain, anisotropy).

Each site's 2x2 distortion matrix C is applied to the unit circle; the
resulting ellipse shows both the anisotropy (axis ratio) and rotation of
the distortion in one glyph. An undistorted site (C = identity) plots as
a perfect circle. Ellipses are colour-coded by a scalar severity metric
(condition number, |det C|, or mean singular value) so problem sites are
visually obvious.

Optionally (GB_DECOMP_ENABLE = True), each site's C is additionally
decomposed into the standard Groom & Bailey (1989) twist / shear / gain /
anisotropy parameters via a numerical least-squares fit (see
`_gb_decompose` docstring for the exact parameterisation and its
limitations), and plotted as a 2x2 grid of per-parameter maps.

@author vrath
@project py4mt
@created 2026-09-13
@modified 2026-09-13

AI-GENERATED CODE NOTICE
-------------------------
This module was generated by Claude Sonnet 5 (Anthropic) on 2026-09-13.
It is AI-generated and has not been independently verified against a
real FEMTIC run; review before production or publication use. The SRTM
basemap step in particular depends on external tooling (`elevation`,
`rasterio`, internet access / GDAL) that could not be exercised in the
environment this script was written in -- treat it as untested until
run once against real data. The Groom-Bailey decomposition was verified
numerically (200 random positive-determinant matrices reconstructed to
< 1e-6 max element error via multi-start least-squares) but not against
an independent reference implementation or real MT data -- see
`_gb_decompose` for details and known limitations (negative-determinant
sites).

Usage
-----
Edit the CONFIG block below and run:

    python femtic_plot_distort.py

Requires
--------
numpy, scipy, matplotlib (required)
rasterio, and either the `elevation` package (auto-download) or a
pre-downloaded GeoTIFF via SRTM_LOCAL_FILE (only required if
BASEMAP_ENABLE = True)
femtic.py, util.py (py4mt) importable on PYTHONPATH / same directory
"""

from __future__ import annotations

import os
import warnings
from pathlib import Path

import numpy as np
from scipy.optimize import least_squares
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon as MplPolygon
from matplotlib.collections import PatchCollection
from matplotlib.colors import LightSource, Normalize
from matplotlib.cm import ScalarMappable

import femtic as fem
import util as utl  # noqa: F401  (imported for consistency with py4mt scripts;
                     # not called directly -- fem.utm_to_model/latlon_to_model
                     # already wrap the util.py zone-aware conversions)

# =====================================================================
# CONFIG -- user-editable parameters
# =====================================================================

# --- input files --------------------------------------------------------
DISTORTION_FILE = "distortion_iter7.dat"   # FEMTIC static distortion file
SITE_DAT        = "site.dat"               # sitelist CSV (mt_make_sitelist.py format:
                                            # name, lat, lon, elev, sitenum, easting, northing)

# --- coordinate system for the plot --------------------------------------
# "model"  -> model-local km   (needs UTM_ORIGIN_E/N, UTM_ZONE, UTM_NORTHERN)
# "utm"    -> absolute UTM km  (needs UTM_ZONE, UTM_NORTHERN)
# "latlon" -> decimal degrees
DISPLAY_COORDS = "latlon"

UTM_ZONE     = 19
UTM_NORTHERN = False            # False = southern hemisphere
UTM_ORIGIN_E = 0.0              # UTM easting  of model origin [m] (only used for "model")
UTM_ORIGIN_N = 0.0              # UTM northing of model origin [m] (only used for "model")

# --- distortion matrix options --------------------------------------------
# "full"  -> plot C = C' + I   (undistorted site -> unit circle)
# "prime" -> plot C' directly  (deviation from identity)
DISTORTION_KIND = "full"

# ellipse size: "auto" scales to a fraction of the median nearest-neighbour
# site spacing (in plot units); or give an explicit float directly in plot
# units (km for "utm"/"model", degrees for "latlon")
ELLIPSE_SCALE    = "auto"
ELLIPSE_FRACTION = 0.4          # used only when ELLIPSE_SCALE == "auto"
ELLIPSE_NPTS     = 91           # ellipse outline resolution

# colour-code ellipses by a distortion-severity metric:
# "condition"   -> singular-value ratio sigma_max / sigma_min (Lilley, 2016)
# "determinant" -> |det(C)|
# "gain"        -> mean singular value
COLOR_BY          = "condition"
CMAP_ELLIPSE      = "viridis_r"
ELLIPSE_EDGECOLOR = "black"
ELLIPSE_LW        = 0.8
ELLIPSE_ALPHA     = 0.75

SITE_LABELS    = False          # annotate site names next to ellipses
LABEL_FONTSIZE = 6

# --- Groom-Bailey decomposition panel (optional) --------------------------
# Decomposes C = g * T(twist) * S(shear) * A(anisotropy) via a numerical
# least-squares fit (Groom & Bailey, 1989) and plots the four parameters
# as a 2x2 grid of per-site maps. Only defined for det(C) > 0 (see
# `_gb_decompose` docstring); sites with det(C) <= 0 are marked with a
# grey "x" and excluded from the fit and from each panel's colour scale.
GB_DECOMP_ENABLE   = False
GB_MARKER_SIZE     = 60
GB_CMAP            = "coolwarm"
GB_UNDEFINED_COLOR = "0.6"      # marker colour for det(C) <= 0 sites
GB_FIGSIZE         = (9.0, 8.0)
GB_BASENAME_SUFFIX = "_gb"      # GB figure saved as f"{OUTPUT_BASENAME}{GB_BASENAME_SUFFIX}.{fmt}"

# --- SRTM basemap ----------------------------------------------------------
BASEMAP_ENABLE      = True
SRTM_PRODUCT        = "SRTM1"   # "SRTM1" (~30 m) or "SRTM3" (~90 m); passed to `elevation`
SRTM_CACHE_DIR      = "./srtm_cache"
SRTM_LOCAL_FILE     = None      # path to a pre-downloaded GeoTIFF; bypasses download when set
SRTM_MARGIN_DEG     = 0.15      # bounding-box margin around the sites [deg]
HILLSHADE_AZIMUTH   = 315.0
HILLSHADE_ALTITUDE  = 45.0
HILLSHADE_VERT_EXAG = 1.0
BASEMAP_CMAP        = "Greys"
BASEMAP_ALPHA       = 0.9

# --- figure / output -----------------------------------------------------
FIGSIZE             = (8.0, 7.0)
DPI                 = 200
TICK_FONTSIZE       = 8
LABEL_FONTSIZE_AXES = 9
TITLE               = "FEMTIC static distortion matrices"
SHOW                = False

# Output files: one file per entry in OUTPUT_FORMATS, named
# f"{OUTPUT_BASENAME}.{fmt}" (and f"{OUTPUT_BASENAME}{GB_BASENAME_SUFFIX}.{fmt}"
# for the optional GB panel). Any format Matplotlib's savefig understands
# is allowed, e.g. ["png"], ["pdf", "jpg"], ["png", "pdf", "svg"].
OUTPUT_BASENAME = "femtic_distortion_ellipses"
OUTPUT_FORMATS  = ["png"]

# =====================================================================
# End of CONFIG
# =====================================================================


def _read_distortion_site_ids(path):
    """Return the site-ID column of a FEMTIC distortion file, in file order.

    ``fem.read_distortion_file`` parses this same column internally but
    does not return it, so it is re-read here to keep the two arrays
    (matrices, IDs) aligned without assuming any particular ordering in
    ``site.dat``.
    """
    lines = Path(path).read_text().strip().splitlines()
    ids = []
    for line in lines[1:]:
        parts = line.split()
        if not parts:
            continue
        ids.append(int(parts[0]))
    return ids


def _load_sites_with_distortion(distortion_file, site_dat, distortion_kind):
    """Merge FEMTIC distortion matrices with site.dat coordinates.

    Returns a list of dicts, one per matched site, with keys
    ``sitenum, name, lat, lon, elev, easting, northing, C``.
    """
    c, c_dash = fem.read_distortion_file(distortion_file)
    site_ids = _read_distortion_site_ids(distortion_file)
    if len(site_ids) != len(c):
        raise RuntimeError(
            f"{distortion_file}: parsed {len(site_ids)} site IDs but "
            f"{len(c)} matrices -- check the file format."
        )

    site_records = fem.read_site_dat(site_dat)
    by_sitenum = {r["sitenum"]: r for r in site_records}

    sites = []
    missing = []
    for sid, C, Cp in zip(site_ids, c, c_dash):
        rec = by_sitenum.get(sid)
        if rec is None:
            missing.append(sid)
            continue
        sites.append(dict(
            sitenum=sid,
            name=rec["name"],
            lat=rec["lat"],
            lon=rec["lon"],
            elev=rec["elev"],
            easting=rec["easting"],
            northing=rec["northing"],
            C=(C if distortion_kind == "full" else Cp),
        ))
    if missing:
        warnings.warn(
            f"{len(missing)} distortion-file site number(s) not found in "
            f"{site_dat}: {missing}"
        )
    if not sites:
        raise RuntimeError(
            "No distortion-file site numbers matched any entry in "
            f"{site_dat} -- check that DISTORTION_FILE and SITE_DAT "
            "correspond to the same run."
        )
    return sites


def _ellipse_points(C, n=91):
    """Image of the unit circle under 2x2 matrix C, as (x, y) arrays."""
    theta = np.linspace(0.0, 2.0 * np.pi, n)
    circle = np.vstack([np.cos(theta), np.sin(theta)])
    out = C @ circle
    return out[0], out[1]


def _severity(C, metric):
    """Scalar distortion-severity metric for a 2x2 matrix C."""
    s = np.linalg.svd(C, compute_uv=False)
    if metric == "condition":
        return float(s[0] / s[1]) if s[1] > 0 else np.inf
    if metric == "determinant":
        return float(abs(np.linalg.det(C)))
    if metric == "gain":
        return float(np.mean(s))
    raise ValueError(
        f"_severity: unknown metric={metric!r}. "
        "Choose 'condition', 'determinant', or 'gain'."
    )


def _median_nn_spacing(xs, ys):
    """Median nearest-neighbour distance among a set of 2-D points."""
    n = len(xs)
    if n < 2:
        return 1.0
    xs = np.asarray(xs)
    ys = np.asarray(ys)
    d = np.hypot(xs[:, None] - xs[None, :], ys[:, None] - ys[None, :])
    np.fill_diagonal(d, np.inf)
    return float(np.median(d.min(axis=1)))


def _gb_model(params):
    """C(twist, shear, s, g) = g * T(twist) @ S(shear) @ diag(1+s, 1-s).

    T(twist) is a pure rotation; S(shear) = [[cos, sin], [sin, cos]] is a
    symmetric shear along the +/-45 deg diagonal axes; A = diag(1+s, 1-s)
    is the anisotropy ("channelling") term. This is algebraically
    equivalent to the classic Groom & Bailey (1989) tan-based
    T/S/A matrices (t = tan(twist), e = tan(shear)), just written directly
    in terms of bounded angles, which is nicer to fit numerically.
    """
    tau, chi, s, g = params
    T = np.array([[np.cos(tau), -np.sin(tau)], [np.sin(tau), np.cos(tau)]])
    S = np.array([[np.cos(chi), np.sin(chi)], [np.sin(chi), np.cos(chi)]])
    A = np.diag([1.0 + s, 1.0 - s])
    return g * T @ S @ A


def _gb_decompose(C, *, rel_tol=1e-4):
    """Groom & Bailey (1989) twist/shear/gain/anisotropy decomposition of C.

    Solves ``C = g * T(twist) @ S(shear) @ diag(1+s, 1-s)`` for
    ``twist, shear in (-45 deg, 45 deg]``, ``s in (-1, 1)``, ``g > 0`` via
    a bounded, multi-start least-squares fit (see `_gb_model`). This is a
    4-parameter fit to the 4 independent entries of C, so an exact fit
    (residual ~ 0) is expected whenever one exists.

    Limitation -- negative-determinant sites: ``det(C_model)`` is always
    ``>= 0`` for this parameterisation (``det(T)=1``, ``det(S)=cos(2*shear)
    >= 0`` within the fitted range, ``det(A)=1-s**2 >= 0``), so a real
    distortion matrix with ``det(C) < 0`` cannot be exactly reproduced.
    This is a known property of the classic Groom-Bailey model, not a bug
    here -- see Lilley (2016, doi:10.1071/EG14093), "Negative
    determinants: the situation with distortion matrices, and
    Groom-Bailey analysis". Such sites are flagged by returning ``None``;
    use the ellipse/condition-number plot (SVD-based, always defined) for
    them instead.

    Returns
    -------
    dict with keys ``twist_deg, shear_deg, gain, anisotropy`` (``s``), or
    ``None`` if ``det(C) <= 0`` or the fit did not converge to a good
    reconstruction (residual above ``rel_tol`` relative to ``norm(C)``).
    """
    if np.linalg.det(C) <= 0:
        return None

    def resid(params):
        return (_gb_model(params) - C).ravel()

    g0 = float(np.sqrt(abs(np.linalg.det(C)))) or 1.0
    starts = (
        [0.0, 0.0, 0.0, g0],
        [0.3, -0.3, 0.2, g0],
        [-0.3, 0.3, -0.2, g0],
    )
    bounds = (
        [-np.pi / 4, -np.pi / 4, -0.999, 1e-9],
        [np.pi / 4, np.pi / 4, 0.999, np.inf],
    )
    best = None
    for x0 in starts:
        res = least_squares(resid, x0, bounds=bounds)
        if best is None or res.cost < best.cost:
            best = res

    c_norm = float(np.linalg.norm(C))
    resid_norm = float(np.linalg.norm(resid(best.x)))
    if c_norm > 0 and resid_norm / c_norm > rel_tol:
        warnings.warn(
            f"_gb_decompose: fit residual {resid_norm:.3g} exceeds "
            f"{rel_tol:g} * ||C|| ({c_norm:.3g}) -- decomposition may be "
            "unreliable for this site."
        )
        return None

    tau, chi, s, g = best.x
    return dict(
        twist_deg=float(np.degrees(tau)),
        shear_deg=float(np.degrees(chi)),
        gain=float(g),
        anisotropy=float(s),
    )


def _utm_epsg(zone, northern):
    """EPSG code for a WGS-84 UTM zone (same convention as util.get_utm_zone)."""
    return (32600 if northern else 32700) + int(zone)


def _get_srtm_hillshade(bounds, target_epsg, cache_dir, product, local_file):
    """Fetch/clip an SRTM tile and return a hillshade ready for imshow().

    Parameters
    ----------
    bounds : (west, south, east, north) in decimal degrees.
    target_epsg : int or None
        None -> keep geographic (EPSG:4326), matching DISPLAY_COORDS="latlon".
        int  -> reproject to this UTM EPSG code, matching "utm"/"model".
    cache_dir : str
        Directory for the downloaded/clipped GeoTIFF.
    product : str
        "SRTM1" or "SRTM3", forwarded to the `elevation` package.
    local_file : str or None
        Pre-downloaded GeoTIFF; if given, no download is attempted.

    Returns
    -------
    dict with keys "extent" ((xmin, xmax, ymin, ymax) in target units,
    metres for a UTM EPSG, degrees for geographic), "hillshade" (2-D
    array), "elevation" (2-D array) -- or None if the basemap could not
    be produced (missing packages, no network, download failure, ...).
    All failure modes are handled by returning None with a warning
    rather than raising, so a missing basemap never aborts the ellipse
    plot itself.
    """
    try:
        import rasterio
        from rasterio.warp import calculate_default_transform, reproject, Resampling
    except ImportError:
        warnings.warn(
            "rasterio is not installed -- skipping SRTM basemap. "
            "Install it, or set BASEMAP_ENABLE = False."
        )
        return None

    tif_path = local_file
    if tif_path is None:
        try:
            import elevation
        except ImportError:
            warnings.warn(
                "The `elevation` package is not installed and no "
                "SRTM_LOCAL_FILE was given -- skipping SRTM basemap. "
                "Install `elevation` (requires GDAL) for auto-download, "
                "or point SRTM_LOCAL_FILE at a pre-downloaded GeoTIFF."
            )
            return None
        os.makedirs(cache_dir, exist_ok=True)
        tif_path = os.path.join(cache_dir, "srtm_clip.tif")
        try:
            elevation.clip(bounds=bounds, output=os.path.abspath(tif_path),
                            product=product)
        except Exception as exc:
            warnings.warn(
                f"SRTM download/clip failed ({exc}) -- skipping basemap. "
                "This usually means no internet access or GDAL/`eio` is "
                "not set up on this machine; set SRTM_LOCAL_FILE to use a "
                "pre-downloaded GeoTIFF instead."
            )
            return None

    try:
        with rasterio.open(tif_path) as src:
            elev = src.read(1).astype(float)
            elev[elev <= -32768] = np.nan  # SRTM void / no-data sentinel
            src_transform = src.transform
            src_crs = src.crs
            src_bounds = src.bounds
            src_width, src_height = src.width, src.height

        if target_epsg is None:
            dst_transform = src_transform
            dst_elev = elev
            height, width = elev.shape
        else:
            dst_crs = rasterio.crs.CRS.from_epsg(target_epsg)
            dst_transform, width, height = calculate_default_transform(
                src_crs, dst_crs, src_width, src_height, *src_bounds
            )
            dst_elev = np.full((height, width), np.nan, dtype=float)
            reproject(
                source=elev,
                destination=dst_elev,
                src_transform=src_transform,
                src_crs=src_crs,
                dst_transform=dst_transform,
                dst_crs=dst_crs,
                resampling=Resampling.bilinear,
            )

        dx = abs(dst_transform.a)
        dy = abs(dst_transform.e)
        if target_epsg is None:
            # Geographic pixel size -> approximate metres at mean latitude,
            # needed only so LightSource.hillshade's slope calculation is
            # not wildly distorted; the displayed axes stay in degrees.
            mean_lat = 0.5 * (bounds[1] + bounds[3])
            dx = dx * 111320.0 * np.cos(np.radians(mean_lat))
            dy = dy * 110540.0

        fill_value = np.nanmin(dst_elev) if np.isfinite(np.nanmin(dst_elev)) else 0.0
        ls = LightSource(azdeg=HILLSHADE_AZIMUTH, altdeg=HILLSHADE_ALTITUDE)
        hillshade = ls.hillshade(
            np.nan_to_num(dst_elev, nan=fill_value),
            vert_exag=HILLSHADE_VERT_EXAG, dx=dx, dy=dy,
        )

        xmin = dst_transform.c
        ymax = dst_transform.f
        xmax = xmin + width * dst_transform.a
        ymin = ymax + height * dst_transform.e
        extent = (xmin, xmax, min(ymin, ymax), max(ymin, ymax))
        return dict(extent=extent, hillshade=hillshade, elevation=dst_elev)

    except Exception as exc:
        warnings.warn(f"Failed to process SRTM raster ({exc}) -- skipping basemap.")
        return None


def _plot_coords(site, display_coords):
    """Site (x, y) in plot units for the chosen DISPLAY_COORDS."""
    if display_coords == "latlon":
        return site["lon"], site["lat"]
    if display_coords == "utm":
        return site["easting"] / 1000.0, site["northing"] / 1000.0
    if display_coords == "model":
        xm, ym = fem.utm_to_model(site["easting"], site["northing"],
                                   UTM_ORIGIN_E, UTM_ORIGIN_N)
        return xm / 1000.0, ym / 1000.0
    raise ValueError(
        f"DISPLAY_COORDS={display_coords!r} not recognised. "
        "Choose 'model', 'utm', or 'latlon'."
    )


def _severity_label(metric):
    return {
        "condition": "condition number  sigma_max / sigma_min",
        "determinant": "|det(C)|",
        "gain": "mean singular value",
    }[metric]


def _axis_labels(display_coords):
    if display_coords == "latlon":
        return "Longitude [deg]", "Latitude [deg]"
    if display_coords == "utm":
        hemi = "N" if UTM_NORTHERN else "S"
        return f"UTM zone {UTM_ZONE}{hemi} Easting [km]", "Northing [km]"
    if display_coords == "model":
        return "Model-local x [km]", "Model-local y [km]"
    raise ValueError(f"DISPLAY_COORDS={display_coords!r} not recognised.")


def _basemap_extent_for(display_coords, bm):
    """Convert an SRTM basemap's native extent into the current plot units."""
    extent = bm["extent"]
    if display_coords == "utm":
        return tuple(v / 1000.0 for v in extent)
    if display_coords == "model":
        xmin, xmax, ymin, ymax = extent
        xmin, ymin = fem.utm_to_model(xmin, ymin, UTM_ORIGIN_E, UTM_ORIGIN_N)
        xmax, ymax = fem.utm_to_model(xmax, ymax, UTM_ORIGIN_E, UTM_ORIGIN_N)
        return xmin / 1000.0, xmax / 1000.0, ymin / 1000.0, ymax / 1000.0
    return extent


def _fetch_basemap_if_enabled(sites, display_coords):
    if not BASEMAP_ENABLE:
        return None
    margin = SRTM_MARGIN_DEG
    lons = [s["lon"] for s in sites]
    lats = [s["lat"] for s in sites]
    bounds = (min(lons) - margin, min(lats) - margin,
              max(lons) + margin, max(lats) + margin)
    target_epsg = None if display_coords == "latlon" else _utm_epsg(
        UTM_ZONE, UTM_NORTHERN
    )
    bm = _get_srtm_hillshade(bounds, target_epsg, SRTM_CACHE_DIR,
                              SRTM_PRODUCT, SRTM_LOCAL_FILE)
    if bm is None:
        print("[femtic_plot_distort] Basemap unavailable -- "
              "plotting on a plain background.")
    return bm


def _draw_basemap(ax, bm, display_coords):
    if bm is None:
        return
    extent = _basemap_extent_for(display_coords, bm)
    ax.imshow(bm["hillshade"], extent=extent, cmap=BASEMAP_CMAP,
              alpha=BASEMAP_ALPHA, origin="upper", zorder=0)


def _savefig_multi(fig, basename, formats, dpi):
    """Save *fig* once per entry in *formats*, returning the paths written.

    A failure saving one format (e.g. missing Pillow for "jpg") is
    reported with a warning and does not prevent the other formats from
    being saved.
    """
    saved = []
    for fmt in formats:
        fmt_clean = str(fmt).lower().lstrip(".")
        path = f"{basename}.{fmt_clean}"
        try:
            if fmt_clean in ("jpg", "jpeg"):
                # JPEG has no alpha channel; force an opaque white background
                # so a transparent figure facecolor doesn't turn black.
                fig.savefig(path, dpi=dpi, format="jpg", facecolor="white")
            else:
                fig.savefig(path, dpi=dpi, format=fmt_clean)
            saved.append(path)
        except Exception as exc:
            warnings.warn(f"Could not save {path!r} ({exc}).")
    return saved


def _plot_ellipse_map(sites, xs, ys, bm, display_coords, color_by,
                      ellipse_scale, ellipse_fraction, ellipse_npts):
    if ellipse_scale == "auto":
        base_radius = ellipse_fraction * _median_nn_spacing(xs, ys)
        if base_radius <= 0:
            base_radius = 1.0
            warnings.warn(
                "Automatic ellipse scale came out non-positive "
                "(degenerate site layout?) -- falling back to 1.0."
            )
    else:
        base_radius = float(ellipse_scale)

    sev = np.array([_severity(s["C"], color_by) for s in sites])

    fig, ax = plt.subplots(figsize=FIGSIZE)
    _draw_basemap(ax, bm, display_coords)

    norm = Normalize(vmin=float(np.nanmin(sev)), vmax=float(np.nanmax(sev)))
    cmap = plt.get_cmap(CMAP_ELLIPSE)

    patches = []
    for s, x0, y0 in zip(sites, xs, ys):
        ex, ey = _ellipse_points(s["C"], n=ellipse_npts)
        verts = np.column_stack([x0 + base_radius * ex, y0 + base_radius * ey])
        patches.append(MplPolygon(verts, closed=True))

    face_colors = [cmap(norm(v)) for v in sev]
    pc = PatchCollection(patches, facecolor=face_colors,
                         edgecolor=ELLIPSE_EDGECOLOR, linewidths=ELLIPSE_LW,
                         alpha=ELLIPSE_ALPHA, zorder=5)
    ax.add_collection(pc)
    ax.plot(xs, ys, "+", color="black", ms=4, zorder=6)

    if SITE_LABELS:
        for s, x0, y0 in zip(sites, xs, ys):
            ax.annotate(s["name"], (x0, y0), fontsize=LABEL_FONTSIZE,
                       xytext=(3, 3), textcoords="offset points", zorder=7)

    sm = ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, shrink=0.8)
    cbar.set_label(_severity_label(color_by), fontsize=LABEL_FONTSIZE_AXES)
    cbar.ax.tick_params(labelsize=TICK_FONTSIZE)

    xlabel, ylabel = _axis_labels(display_coords)
    ax.set_xlabel(xlabel, fontsize=LABEL_FONTSIZE_AXES)
    ax.set_ylabel(ylabel, fontsize=LABEL_FONTSIZE_AXES)
    ax.tick_params(labelsize=TICK_FONTSIZE)
    ax.set_aspect("equal")
    ax.set_title(TITLE, fontsize=LABEL_FONTSIZE_AXES + 1)
    ax.autoscale_view()
    fig.tight_layout()
    return fig


def _plot_gb_panel(sites, xs, ys, bm, display_coords):
    """2x2 panel of Groom-Bailey twist / shear / gain / anisotropy maps."""
    gb = [_gb_decompose(s["C"]) for s in sites]
    n_undefined = sum(1 for g in gb if g is None)
    if n_undefined:
        warnings.warn(
            f"{n_undefined} of {len(sites)} site(s) have det(C) <= 0 (or a "
            "non-converged fit) and are excluded from the Groom-Bailey "
            "panel colour scales; shown as grey 'x' markers. See "
            "_gb_decompose docstring."
        )

    panels = (
        ("twist_deg", "Twist [deg]"),
        ("shear_deg", "Shear [deg]"),
        ("gain", "Gain"),
        ("anisotropy", "Anisotropy (split s)"),
    )

    fig, axs = plt.subplots(2, 2, figsize=GB_FIGSIZE, sharex=True, sharey=True)
    xlabel, ylabel = _axis_labels(display_coords)

    for ax, (key, label) in zip(axs.ravel(), panels):
        _draw_basemap(ax, bm, display_coords)

        defined = [(x, y, g[key]) for x, y, g in zip(xs, ys, gb) if g is not None]
        undefined = [(x, y) for x, y, g in zip(xs, ys, gb) if g is None]

        if defined:
            dx, dy, dv = map(np.array, zip(*defined))
            sca = ax.scatter(dx, dy, c=dv, cmap=GB_CMAP, s=GB_MARKER_SIZE,
                             edgecolor="black", linewidths=0.5, zorder=5)
            cbar = fig.colorbar(sca, ax=ax, shrink=0.85)
            cbar.ax.tick_params(labelsize=TICK_FONTSIZE)
        if undefined:
            ux, uy = map(np.array, zip(*undefined))
            ax.scatter(ux, uy, marker="x", color=GB_UNDEFINED_COLOR,
                      s=GB_MARKER_SIZE, zorder=5,
                      label="det(C) <= 0 / not converged")
            ax.legend(fontsize=LABEL_FONTSIZE, loc="best")

        ax.set_title(label, fontsize=LABEL_FONTSIZE_AXES)
        ax.tick_params(labelsize=TICK_FONTSIZE)
        ax.set_aspect("equal")

    for ax in axs[-1, :]:
        ax.set_xlabel(xlabel, fontsize=LABEL_FONTSIZE_AXES)
    for ax in axs[:, 0]:
        ax.set_ylabel(ylabel, fontsize=LABEL_FONTSIZE_AXES)

    fig.suptitle("Groom-Bailey decomposition of C "
                 "(Groom & Bailey, 1989, doi:10.1029/JB094iB02p01913)",
                 fontsize=LABEL_FONTSIZE_AXES + 1)
    fig.tight_layout()
    return fig


def plot_distortion_ellipses(
    distortion_file=DISTORTION_FILE,
    site_dat=SITE_DAT,
    display_coords=DISPLAY_COORDS,
    distortion_kind=DISTORTION_KIND,
    ellipse_scale=ELLIPSE_SCALE,
    ellipse_fraction=ELLIPSE_FRACTION,
    ellipse_npts=ELLIPSE_NPTS,
    color_by=COLOR_BY,
    gb_decomp_enable=GB_DECOMP_ENABLE,
    output_basename=OUTPUT_BASENAME,
    output_formats=OUTPUT_FORMATS,
):
    """Read a FEMTIC distortion file + site.dat and plot distortion ellipses.

    Also produces the optional Groom-Bailey 2x2 decomposition panel when
    ``gb_decomp_enable`` (or the module-level ``GB_DECOMP_ENABLE`` CONFIG
    flag) is True.

    All tunable parameters double as module-level CONFIG variables (see
    the CONFIG block above); this function signature exists so the plot
    can also be called programmatically, e.g. from an ensemble-QC loop.

    Returns
    -------
    (ellipse_fig, gb_fig) : gb_fig is None when gb_decomp_enable is False.
    """
    if display_coords not in ("model", "utm", "latlon"):
        raise ValueError(
            f"DISPLAY_COORDS={display_coords!r} not recognised. "
            "Choose 'model', 'utm', or 'latlon'."
        )
    if distortion_kind not in ("full", "prime"):
        raise ValueError(
            f"DISTORTION_KIND={distortion_kind!r} not recognised. "
            "Choose 'full' or 'prime'."
        )
    if color_by not in ("condition", "determinant", "gain"):
        raise ValueError(
            f"COLOR_BY={color_by!r} not recognised. "
            "Choose 'condition', 'determinant', or 'gain'."
        )

    sites = _load_sites_with_distortion(distortion_file, site_dat, distortion_kind)

    xs, ys = [], []
    for s in sites:
        x, y = _plot_coords(s, display_coords)
        xs.append(x)
        ys.append(y)
    xs = np.asarray(xs)
    ys = np.asarray(ys)

    bm = _fetch_basemap_if_enabled(sites, display_coords)

    ellipse_fig = _plot_ellipse_map(
        sites, xs, ys, bm, display_coords, color_by,
        ellipse_scale, ellipse_fraction, ellipse_npts,
    )
    saved = _savefig_multi(ellipse_fig, output_basename, output_formats, DPI)
    if SHOW:
        plt.show()
    print(f"[femtic_plot_distort] {len(sites)} site(s) plotted -> "
          f"{', '.join(saved) if saved else '(no files saved)'}")

    gb_fig = None
    if gb_decomp_enable:
        gb_fig = _plot_gb_panel(sites, xs, ys, bm, display_coords)
        gb_basename = f"{output_basename}{GB_BASENAME_SUFFIX}"
        gb_saved = _savefig_multi(gb_fig, gb_basename, output_formats, DPI)
        if SHOW:
            plt.show()
        print(f"[femtic_plot_distort] Groom-Bailey panel -> "
              f"{', '.join(gb_saved) if gb_saved else '(no files saved)'}")

    plt.close(ellipse_fig)
    if gb_fig is not None:
        plt.close(gb_fig)

    return ellipse_fig, gb_fig


if __name__ == "__main__":
    plot_distortion_ellipses()
