"""
femtic_plot_nrms.py
====================

Plot per-site normalised RMS (nRMS) data misfit from a FEMTIC run as
colour-coded glyphs on a map, optionally over an SRTM-derived hillshade
basemap. Modeled on `femtic_plot_distort.py` (same CONFIG-block style,
coordinate-system choice, SRTM basemap, and multi-format output).

Data flow
---------
1. The best (smallest-nRMS) iteration is identified from `femtic.cnv` via
   `fem.get_nrms(FEMTIC_DIR)` -- this is FEMTIC's own authoritative
   whole-run nRMS trace; nothing here recomputes it.
2. Per-site residuals for *that* iteration come from `data_iter<N>.h5`
   (N = the iteration selected in step 1), read via
   `femtic_hdf5_readers.read_data_hdf5` -- `femtic.cnv` itself has no
   per-site breakdown, only one row per iteration.
3. Each site's nRMS is the RMS of its normalised residuals,

       nRMS_site = sqrt( mean_i[ ((obs_i - cal_i) / err_i)**2 ] )

   pooled over every frequency, component, and station type (`STATION_TYPES`)
   at that site.

A well-fit site should sit near nRMS = 1; the default colour map is
diverging and centred there, so under- and over-fit sites are visually
distinct at a glance. Marker size scales with nRMS by default. An optional
threshold highlights outlier sites with a coloured marker ring.

@author vrath
@project py4mt
@created 2026-09-13
@modified 2026-09-13

AI-GENERATED CODE NOTICE
-------------------------
This module was generated by Claude Sonnet 5 (Anthropic) on 2026-09-13.
It is AI-generated and has not been independently verified against a
real FEMTIC run; review before production or publication use.

This script's HDF5 reading depends entirely on `femtic_hdf5_readers.py`
(supplied separately, not written in this session) and that module's own
documentation is explicit that its `data_iter<N>.h5` schema was
"reconstructed from prior FEMTIC C++ porting sessions, not re-verified
against a live .h5 file" -- component order/count within `cal`/`obs`/`err`
is called out there as "provisional until checked against a real file".
That uncertainty is inherited unchanged here: if `read_data_hdf5` raises
`FemticHDF5SchemaError`, or the per-site nRMS values look implausible,
that almost certainly means the schema assumption is wrong for your
build, not a bug in the residual-pooling arithmetic below (which was
verified independently -- see the companion readme's "Verification
performed" section) -- run `femtic_hdf5_readers.inspect_file()` on one
`data_iter<N>.h5` and compare against what `read_data_hdf5` expects.

The `station_id` <-> `site.dat` `sitenum` matching (`_resolve_station_ids`)
assumes the two use the same integer convention (tried as-is first, then
with a +1 offset as a fallback for a possible 0-based/1-based mismatch);
this has not been checked against a real file either. The SRTM basemap
step depends on external tooling (`elevation`, `rasterio`, internet
access / GDAL) that could not be exercised in the environment this script
was written in -- treat it as untested until run once against real data.

Usage
-----
Edit the CONFIG block below and run:

    python femtic_plot_nrms.py

Requires
--------
numpy, matplotlib (required)
h5py (required -- via femtic_hdf5_readers.py, which must be importable
alongside this script)
rasterio, and either the `elevation` package (auto-download) or a
pre-downloaded GeoTIFF via SRTM_LOCAL_FILE (only required if
BASEMAP_ENABLE = True)
femtic.py, util.py, femtic_hdf5_readers.py (py4mt) importable on
PYTHONPATH / same directory
"""

from __future__ import annotations

import os
import warnings
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LightSource, TwoSlopeNorm

import femtic as fem
import util as utl  # noqa: F401  (imported for consistency with py4mt scripts;
                     # not called directly -- fem.utm_to_model/latlon_to_model
                     # already wrap the util.py zone-aware conversions)
import femtic_hdf5_readers as hdf5r

# =====================================================================
# CONFIG -- user-editable parameters
# =====================================================================

# --- input files --------------------------------------------------------
# Directory containing femtic.cnv (used to pick the best/smallest-nRMS
# iteration) and the data_iter<N>.h5 files (used for the per-site
# residual breakdown at that iteration).
FEMTIC_DIR = "."

# Filename template for the per-iteration HDF5 data file, relative to
# FEMTIC_DIR. Must contain the literal "{iter}" placeholder, filled in
# with the best iteration number found in femtic.cnv.
DATA_ITER_TEMPLATE = "data_iter{iter}.h5"

# Station type(s) inside data_iter<N>.h5 to pool into the per-site nRMS
# (e.g. "MT", "VTF", "PT" -- see femtic_hdf5_readers.KNOWN_STATION_TYPE_NAMES).
# None -> use every station-type group actually present in the file.
STATION_TYPES = None

# Sitelist CSV (mt_make_sitelist.py format: name, lat, lon, elev, sitenum,
# easting, northing), read via fem.read_site_dat for coordinates. Sites
# are matched to data_iter<N>.h5's station_id via _resolve_station_ids.
SITE_DAT = "site.dat"

# --- coordinate system for the plot --------------------------------------
# "model"  -> model-local km   (needs UTM_ORIGIN_E/N, UTM_ZONE, UTM_NORTHERN)
# "utm"    -> absolute UTM km  (needs UTM_ZONE, UTM_NORTHERN)
# "latlon" -> decimal degrees
DISPLAY_COORDS = "latlon"

UTM_ZONE     = 19
UTM_NORTHERN = False            # False = southern hemisphere
UTM_ORIGIN_E = 0.0              # UTM easting  of model origin [m] (only used for "model")
UTM_ORIGIN_N = 0.0              # UTM northing of model origin [m] (only used for "model")

# --- nRMS reduction --------------------------------------------------------
ERR_MIN = 0.0   # (obs, cal, err) triples with err <= ERR_MIN are excluded
                # from the misfit sum -- FEMTIC/observe.dat conventions use
                # this to flag unused/placeholder components or frequencies.

# --- glyph appearance -------------------------------------------------------
GLYPH_MARKER    = "o"
GLYPH_SIZE_MODE = "scaled"      # "fixed" -> GLYPH_SIZE_FIXED for every site
                                 # "scaled" -> marker area grows with nRMS
GLYPH_SIZE_FIXED = 80
GLYPH_SIZE_MIN   = 30           # "scaled" mode: size at the lowest nRMS
GLYPH_SIZE_MAX   = 260          # "scaled" mode: size at the highest nRMS
GLYPH_EDGECOLOR  = "black"
GLYPH_LW         = 0.6

CMAP_NRMS      = "RdBu_r"       # diverging colormap, centred on NRMS_REFERENCE
NRMS_REFERENCE = 1.0            # target/acceptable nRMS -> centre colour
NRMS_VMIN      = None           # None -> auto from data (symmetric around NRMS_REFERENCE)
NRMS_VMAX      = None

# Outlier sites with nRMS above this threshold get a highlighted marker
# edge (in addition to their normal fill colour); None disables this.
NRMS_FLAG_THRESHOLD  = None     # e.g. 3.0
NRMS_FLAG_EDGECOLOR  = "magenta"
NRMS_FLAG_LW         = 2.2

SITE_LABELS    = False          # annotate site names next to glyphs
LABEL_FONTSIZE = 6

# --- SRTM basemap ----------------------------------------------------------
BASEMAP_ENABLE      = True
SRTM_PRODUCT        = "SRTM1"   # "SRTM1" (~30 m) or "SRTM3" (~90 m); passed to `elevation`
SRTM_CACHE_DIR      = "./srtm_cache"
SRTM_LOCAL_FILE     = None      # path to a pre-downloaded GeoTIFF; bypasses download when set
SRTM_MARGIN_DEG     = 0.15      # bounding-box margin around the sites [deg]
HILLSHADE_AZIMUTH   = 315.0
HILLSHADE_ALTITUDE  = 45.0
HILLSHADE_VERT_EXAG = 1.0
BASEMAP_CMAP        = "Greys"
BASEMAP_ALPHA       = 0.9

# --- figure / output -----------------------------------------------------
FIGSIZE             = (8.0, 7.0)
DPI                 = 200
TICK_FONTSIZE       = 8
LABEL_FONTSIZE_AXES = 9
TITLE               = "FEMTIC per-site nRMS misfit"
TITLE_SHOW_ITERATION = True     # append "(iteration N, overall nRMS = X)" to TITLE
SHOW                = False

# Output files: one file per entry in OUTPUT_FORMATS, named
# f"{OUTPUT_BASENAME}.{fmt}". Any format Matplotlib's savefig understands
# is allowed, e.g. ["png"], ["pdf", "jpg"], ["png", "pdf", "svg"].
OUTPUT_BASENAME = "femtic_nrms_glyphs"
OUTPUT_FORMATS  = ["png"]

# =====================================================================
# End of CONFIG
# =====================================================================


def _select_best_iteration(femtic_dir):
    """Best (smallest-nRMS) iteration and its nRMS, from femtic.cnv.

    Thin wrapper around fem.get_nrms -- kept as its own function so the
    "where does the authoritative nRMS come from" step is visible and
    separately testable from the per-site HDF5 breakdown below.
    """
    num_best, nrm_best = fem.get_nrms(femtic_dir)
    if num_best < 0:
        raise RuntimeError(
            f"fem.get_nrms found no usable rows in "
            f"{os.path.join(femtic_dir, 'femtic.cnv')!r}."
        )
    return num_best, nrm_best


def _resolve_station_ids(station_id, valid_sitenums, station_type):
    """Match a station-type block's station_id array to site.dat sitenums.

    Requires *every* unique station_id value to be a valid sitenum before
    accepting a mapping -- a partial overlap (e.g. some IDs coincidentally
    valid either way) is not good enough evidence and is treated as no
    match, to avoid silently mis-mapping the IDs that don't happen to
    collide. Tries station_id as-is first; if that isn't a full match but
    station_id + 1 is, assumes a 0-based/1-based mismatch and uses that
    instead (with a warning). Raises if neither is a full match, rather
    than silently pooling residuals under the wrong site.
    """
    station_id = np.asarray(station_id).astype(int)
    uniq = np.unique(station_id)
    if set(uniq) <= valid_sitenums:
        return station_id
    uniq_plus = np.unique(station_id + 1)
    if set(uniq_plus) <= valid_sitenums:
        warnings.warn(
            f"{station_type!r} station_id values did not all match a "
            "SITE_DAT sitenum directly; using station_id + 1 (0-based -> "
            "1-based convention mismatch) instead, since that mapping "
            "fully matches. Verify this against a real file -- "
            "femtic_hdf5_readers.py's own docs mark this indexing as "
            "unconfirmed."
        )
        return station_id + 1
    raise RuntimeError(
        f"{station_type!r} station_id values {list(uniq)[:10]}"
        f"{'...' if len(uniq) > 10 else ''} do not all match a SITE_DAT "
        f"sitenum, as-is (overlap: {sorted(set(uniq) & valid_sitenums)}) "
        f"or +1 (overlap: {sorted(set(uniq_plus) & valid_sitenums)}). "
        "Check that SITE_DAT corresponds to this run, or run "
        "femtic_hdf5_readers.inspect_file() on the data file to check the "
        "station_id convention."
    )


def _load_nrms_per_site(femtic_dir, data_iter_template, site_dat,
                        station_types=None, err_min=0.0):
    """Compute per-site nRMS at FEMTIC's best iteration.

    Returns (sites, best_iter, best_nrms):
      sites : list of dicts with keys
              sitenum, name, lat, lon, elev, easting, northing, nrms, n_obs
      best_iter : int, the iteration femtic.cnv reports as smallest-nRMS
      best_nrms : float, that iteration's overall nRMS (from femtic.cnv)
    """
    best_iter, best_nrms = _select_best_iteration(femtic_dir)

    if "{iter}" not in data_iter_template:
        raise ValueError(
            f"DATA_ITER_TEMPLATE={data_iter_template!r} must contain the "
            "literal placeholder '{iter}'."
        )
    data_path = os.path.join(femtic_dir, data_iter_template.format(iter=best_iter))
    if not os.path.isfile(data_path):
        raise FileNotFoundError(
            f"Best iteration is {best_iter} (nRMS={best_nrms:.4g} per "
            f"femtic.cnv) but {data_path!r} does not exist."
        )

    data = hdf5r.read_data_hdf5(data_path)

    h5_iter = data.attrs.get("iteration")
    if h5_iter is not None and int(h5_iter) != best_iter:
        warnings.warn(
            f"{data_path}'s 'iteration' attribute ({h5_iter}) does not match "
            f"the best iteration reported by femtic.cnv ({best_iter}) -- "
            "using the file as given; check FEMTIC_DIR/DATA_ITER_TEMPLATE "
            "if this is unexpected."
        )

    if not data.by_type:
        raise RuntimeError(
            f"{data_path}: no v1.5.2 per-station-type groups found (only "
            "the legacy flat 'table' layout is present). This script needs "
            "the per-station_id breakdown that only the v1.5.2 layout "
            "exposes; the legacy layout cannot be split back out per site."
        )

    types = station_types if station_types is not None else data.station_types()

    site_records = fem.read_site_dat(site_dat)
    by_sitenum = {r["sitenum"]: r for r in site_records}
    valid_sitenums = set(by_sitenum)

    sq_sum: dict[int, float] = {}
    n_obs: dict[int, int] = {}
    n_types_used = 0

    for typ in types:
        sd = data.by_type.get(typ)
        if sd is None:
            warnings.warn(
                f"Requested station type {typ!r} not found in {data_path} "
                f"(available: {data.station_types()}) -- skipped."
            )
            continue
        n_types_used += 1

        station_id = _resolve_station_ids(sd.station_id, valid_sitenums, typ)
        cal = np.asarray(sd.cal, dtype=float)
        obs = np.asarray(sd.obs, dtype=float)
        err = np.asarray(sd.err, dtype=float)

        resid = obs - cal
        mask = np.isfinite(err) & (err > err_min) & np.isfinite(resid)
        norm_sq = np.zeros_like(resid)
        norm_sq[mask] = (resid[mask] / err[mask]) ** 2

        for row, sitenum in enumerate(station_id):
            valid = mask[row]
            n_valid = int(np.count_nonzero(valid))
            if n_valid == 0:
                continue
            sitenum = int(sitenum)
            sq_sum[sitenum] = sq_sum.get(sitenum, 0.0) + float(np.sum(norm_sq[row][valid]))
            n_obs[sitenum] = n_obs.get(sitenum, 0) + n_valid

    if n_types_used == 0:
        raise RuntimeError(
            f"None of the requested station types {list(types)} were found "
            f"in {data_path} (available: {data.station_types()})."
        )

    sites = []
    missing = []
    for sitenum, ssum in sq_sum.items():
        rec = by_sitenum.get(sitenum)
        if rec is None:
            missing.append(sitenum)
            continue
        n = n_obs[sitenum]
        sites.append(dict(
            sitenum=sitenum,
            name=rec["name"],
            lat=rec["lat"],
            lon=rec["lon"],
            elev=rec["elev"],
            easting=rec["easting"],
            northing=rec["northing"],
            nrms=float(np.sqrt(ssum / n)),
            n_obs=n,
        ))
    if missing:
        warnings.warn(
            f"{len(missing)} station_id(s) from {data_path} not found in "
            f"{site_dat}: {missing}"
        )
    if not sites:
        raise RuntimeError(
            f"No station_id in {data_path} matched any entry in {site_dat} "
            "-- check that SITE_DAT corresponds to this run."
        )
    return sites, best_iter, best_nrms


def _utm_epsg(zone, northern):
    """EPSG code for a WGS-84 UTM zone (same convention as util.get_utm_zone)."""
    return (32600 if northern else 32700) + int(zone)


def _get_srtm_hillshade(bounds, target_epsg, cache_dir, product, local_file):
    """Fetch/clip an SRTM tile and return a hillshade ready for imshow().

    See femtic_plot_distort.py's function of the same name for the full
    parameter/return documentation -- identical implementation, kept
    duplicated here so this script has no dependency on that one.
    """
    try:
        import rasterio
        from rasterio.warp import calculate_default_transform, reproject, Resampling
    except ImportError:
        warnings.warn(
            "rasterio is not installed -- skipping SRTM basemap. "
            "Install it, or set BASEMAP_ENABLE = False."
        )
        return None

    tif_path = local_file
    if tif_path is None:
        try:
            import elevation
        except ImportError:
            warnings.warn(
                "The `elevation` package is not installed and no "
                "SRTM_LOCAL_FILE was given -- skipping SRTM basemap. "
                "Install `elevation` (requires GDAL) for auto-download, "
                "or point SRTM_LOCAL_FILE at a pre-downloaded GeoTIFF."
            )
            return None
        os.makedirs(cache_dir, exist_ok=True)
        tif_path = os.path.join(cache_dir, "srtm_clip.tif")
        try:
            elevation.clip(bounds=bounds, output=os.path.abspath(tif_path),
                            product=product)
        except Exception as exc:
            warnings.warn(
                f"SRTM download/clip failed ({exc}) -- skipping basemap. "
                "This usually means no internet access or GDAL/`eio` is "
                "not set up on this machine; set SRTM_LOCAL_FILE to use a "
                "pre-downloaded GeoTIFF instead."
            )
            return None

    try:
        with rasterio.open(tif_path) as src:
            elev = src.read(1).astype(float)
            elev[elev <= -32768] = np.nan  # SRTM void / no-data sentinel
            src_transform = src.transform
            src_crs = src.crs
            src_bounds = src.bounds
            src_width, src_height = src.width, src.height

        if target_epsg is None:
            dst_transform = src_transform
            dst_elev = elev
            height, width = elev.shape
        else:
            dst_crs = rasterio.crs.CRS.from_epsg(target_epsg)
            dst_transform, width, height = calculate_default_transform(
                src_crs, dst_crs, src_width, src_height, *src_bounds
            )
            dst_elev = np.full((height, width), np.nan, dtype=float)
            reproject(
                source=elev,
                destination=dst_elev,
                src_transform=src_transform,
                src_crs=src_crs,
                dst_transform=dst_transform,
                dst_crs=dst_crs,
                resampling=Resampling.bilinear,
            )

        dx = abs(dst_transform.a)
        dy = abs(dst_transform.e)
        if target_epsg is None:
            mean_lat = 0.5 * (bounds[1] + bounds[3])
            dx = dx * 111320.0 * np.cos(np.radians(mean_lat))
            dy = dy * 110540.0

        fill_value = np.nanmin(dst_elev) if np.isfinite(np.nanmin(dst_elev)) else 0.0
        ls = LightSource(azdeg=HILLSHADE_AZIMUTH, altdeg=HILLSHADE_ALTITUDE)
        hillshade = ls.hillshade(
            np.nan_to_num(dst_elev, nan=fill_value),
            vert_exag=HILLSHADE_VERT_EXAG, dx=dx, dy=dy,
        )

        xmin = dst_transform.c
        ymax = dst_transform.f
        xmax = xmin + width * dst_transform.a
        ymin = ymax + height * dst_transform.e
        extent = (xmin, xmax, min(ymin, ymax), max(ymin, ymax))
        return dict(extent=extent, hillshade=hillshade, elevation=dst_elev)

    except Exception as exc:
        warnings.warn(f"Failed to process SRTM raster ({exc}) -- skipping basemap.")
        return None


def _plot_coords(site, display_coords):
    """Site (x, y) in plot units for the chosen DISPLAY_COORDS."""
    if display_coords == "latlon":
        return site["lon"], site["lat"]
    if display_coords == "utm":
        return site["easting"] / 1000.0, site["northing"] / 1000.0
    if display_coords == "model":
        xm, ym = fem.utm_to_model(site["easting"], site["northing"],
                                   UTM_ORIGIN_E, UTM_ORIGIN_N)
        return xm / 1000.0, ym / 1000.0
    raise ValueError(
        f"DISPLAY_COORDS={display_coords!r} not recognised. "
        "Choose 'model', 'utm', or 'latlon'."
    )


def _axis_labels(display_coords):
    if display_coords == "latlon":
        return "Longitude [deg]", "Latitude [deg]"
    if display_coords == "utm":
        hemi = "N" if UTM_NORTHERN else "S"
        return f"UTM zone {UTM_ZONE}{hemi} Easting [km]", "Northing [km]"
    if display_coords == "model":
        return "Model-local x [km]", "Model-local y [km]"
    raise ValueError(f"DISPLAY_COORDS={display_coords!r} not recognised.")


def _basemap_extent_for(display_coords, bm):
    """Convert an SRTM basemap's native extent into the current plot units."""
    extent = bm["extent"]
    if display_coords == "utm":
        return tuple(v / 1000.0 for v in extent)
    if display_coords == "model":
        xmin, xmax, ymin, ymax = extent
        xmin, ymin = fem.utm_to_model(xmin, ymin, UTM_ORIGIN_E, UTM_ORIGIN_N)
        xmax, ymax = fem.utm_to_model(xmax, ymax, UTM_ORIGIN_E, UTM_ORIGIN_N)
        return xmin / 1000.0, xmax / 1000.0, ymin / 1000.0, ymax / 1000.0
    return extent


def _fetch_basemap_if_enabled(sites, display_coords):
    if not BASEMAP_ENABLE:
        return None
    margin = SRTM_MARGIN_DEG
    lons = [s["lon"] for s in sites]
    lats = [s["lat"] for s in sites]
    bounds = (min(lons) - margin, min(lats) - margin,
              max(lons) + margin, max(lats) + margin)
    target_epsg = None if display_coords == "latlon" else _utm_epsg(
        UTM_ZONE, UTM_NORTHERN
    )
    bm = _get_srtm_hillshade(bounds, target_epsg, SRTM_CACHE_DIR,
                              SRTM_PRODUCT, SRTM_LOCAL_FILE)
    if bm is None:
        print("[femtic_plot_nrms] Basemap unavailable -- "
              "plotting on a plain background.")
    return bm


def _draw_basemap(ax, bm, display_coords):
    if bm is None:
        return
    extent = _basemap_extent_for(display_coords, bm)
    ax.imshow(bm["hillshade"], extent=extent, cmap=BASEMAP_CMAP,
              alpha=BASEMAP_ALPHA, origin="upper", zorder=0)


def _savefig_multi(fig, basename, formats, dpi):
    """Save *fig* once per entry in *formats*, returning the paths written.

    A failure saving one format (e.g. missing Pillow for "jpg") is
    reported with a warning and does not prevent the other formats from
    being saved.
    """
    saved = []
    for fmt in formats:
        fmt_clean = str(fmt).lower().lstrip(".")
        path = f"{basename}.{fmt_clean}"
        try:
            if fmt_clean in ("jpg", "jpeg"):
                fig.savefig(path, dpi=dpi, format="jpg", facecolor="white")
            else:
                fig.savefig(path, dpi=dpi, format=fmt_clean)
            saved.append(path)
        except Exception as exc:
            warnings.warn(f"Could not save {path!r} ({exc}).")
    return saved


def _glyph_sizes(nrms, mode, fixed, smin, smax):
    nrms = np.asarray(nrms, dtype=float)
    if mode == "fixed":
        return np.full_like(nrms, fixed)
    if mode == "scaled":
        lo, hi = float(np.nanmin(nrms)), float(np.nanmax(nrms))
        if hi <= lo:
            return np.full_like(nrms, 0.5 * (smin + smax))
        frac = (nrms - lo) / (hi - lo)
        return smin + frac * (smax - smin)
    raise ValueError(
        f"GLYPH_SIZE_MODE={mode!r} not recognised. Choose 'fixed' or 'scaled'."
    )


def plot_nrms_glyphs(
    femtic_dir=FEMTIC_DIR,
    data_iter_template=DATA_ITER_TEMPLATE,
    site_dat=SITE_DAT,
    station_types=STATION_TYPES,
    display_coords=DISPLAY_COORDS,
    err_min=ERR_MIN,
    output_basename=OUTPUT_BASENAME,
    output_formats=OUTPUT_FORMATS,
):
    """Plot per-site nRMS at FEMTIC's best (smallest-nRMS) iteration.

    All tunable parameters double as module-level CONFIG variables (see
    the CONFIG block above); this function signature exists so the plot
    can also be called programmatically, e.g. from an ensemble-QC loop.

    Returns
    -------
    fig : matplotlib Figure
    """
    if display_coords not in ("model", "utm", "latlon"):
        raise ValueError(
            f"DISPLAY_COORDS={display_coords!r} not recognised. "
            "Choose 'model', 'utm', or 'latlon'."
        )

    sites, best_iter, best_nrms = _load_nrms_per_site(
        femtic_dir, data_iter_template, site_dat,
        station_types=station_types, err_min=err_min,
    )

    xs, ys, nrms = [], [], []
    for s in sites:
        x, y = _plot_coords(s, display_coords)
        xs.append(x)
        ys.append(y)
        nrms.append(s["nrms"])
    xs = np.asarray(xs)
    ys = np.asarray(ys)
    nrms = np.asarray(nrms)

    bm = _fetch_basemap_if_enabled(sites, display_coords)

    fig, ax = plt.subplots(figsize=FIGSIZE)
    _draw_basemap(ax, bm, display_coords)

    vmin = NRMS_VMIN
    vmax = NRMS_VMAX
    if vmin is None or vmax is None:
        spread = max(
            abs(float(np.nanmax(nrms)) - NRMS_REFERENCE),
            abs(NRMS_REFERENCE - float(np.nanmin(nrms))),
            1e-6,
        )
        vmin = NRMS_REFERENCE - spread if vmin is None else vmin
        vmax = NRMS_REFERENCE + spread if vmax is None else vmax
    norm = TwoSlopeNorm(vcenter=NRMS_REFERENCE, vmin=vmin, vmax=vmax)
    cmap = plt.get_cmap(CMAP_NRMS)

    sizes = _glyph_sizes(nrms, GLYPH_SIZE_MODE, GLYPH_SIZE_FIXED,
                         GLYPH_SIZE_MIN, GLYPH_SIZE_MAX)

    sca = ax.scatter(xs, ys, c=nrms, s=sizes, cmap=cmap, norm=norm,
                     marker=GLYPH_MARKER, edgecolor=GLYPH_EDGECOLOR,
                     linewidths=GLYPH_LW, zorder=5)

    if NRMS_FLAG_THRESHOLD is not None:
        flagged = nrms > NRMS_FLAG_THRESHOLD
        if np.any(flagged):
            ax.scatter(xs[flagged], ys[flagged], s=sizes[flagged] * 1.35,
                      facecolors="none", edgecolors=NRMS_FLAG_EDGECOLOR,
                      linewidths=NRMS_FLAG_LW, marker=GLYPH_MARKER, zorder=6,
                      label=f"nRMS > {NRMS_FLAG_THRESHOLD:g}")
            ax.legend(fontsize=LABEL_FONTSIZE_AXES, loc="best")

    if SITE_LABELS:
        for s, x0, y0 in zip(sites, xs, ys):
            ax.annotate(s["name"], (x0, y0), fontsize=LABEL_FONTSIZE,
                       xytext=(3, 3), textcoords="offset points", zorder=7)

    cbar = fig.colorbar(sca, ax=ax, shrink=0.8)
    cbar.set_label("nRMS", fontsize=LABEL_FONTSIZE_AXES)
    cbar.ax.axhline(NRMS_REFERENCE, color="black", lw=0.8, ls="--")
    cbar.ax.tick_params(labelsize=TICK_FONTSIZE)

    xlabel, ylabel = _axis_labels(display_coords)
    ax.set_xlabel(xlabel, fontsize=LABEL_FONTSIZE_AXES)
    ax.set_ylabel(ylabel, fontsize=LABEL_FONTSIZE_AXES)
    ax.tick_params(labelsize=TICK_FONTSIZE)
    ax.set_aspect("equal")

    title = TITLE
    if TITLE_SHOW_ITERATION:
        title = f"{title}\n(iteration {best_iter}, overall nRMS = {best_nrms:.3g})"
    ax.set_title(title, fontsize=LABEL_FONTSIZE_AXES + 1)
    ax.autoscale_view()
    fig.tight_layout()

    saved = _savefig_multi(fig, output_basename, output_formats, DPI)
    if SHOW:
        plt.show()
    print(f"[femtic_plot_nrms] iteration {best_iter} (overall nRMS = "
          f"{best_nrms:.4g}): {len(sites)} site(s) plotted "
          f"(median per-site nRMS = {float(np.nanmedian(nrms)):.3g}) -> "
          f"{', '.join(saved) if saved else '(no files saved)'}")
    plt.close(fig)
    return fig


if __name__ == "__main__":
    plot_nrms_glyphs()
